# Generated by Django 3.0.6 on 2020-05-21 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NameBasics',
            fields=[
                ('nconst', models.TextField(primary_key=True, serialize=False)),
                ('primaryname', models.TextField(null=True)),
                ('birthyear', models.IntegerField(null=True)),
                ('deathyear', models.TextField(null=True)),
                ('primaryprofession', models.TextField(null=True)),
                ('knownfortitles', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TitleAkas',
            fields=[
                ('titleid', models.TextField(primary_key=True, serialize=False)),
                ('ordering', models.IntegerField()),
                ('title', models.TextField(null=True)),
                ('region', models.TextField(null=True)),
                ('language', models.TextField(null=True)),
                ('types', models.TextField(null=True)),
                ('attributes', models.TextField(null=True)),
                ('isoriginaltitle', models.IntegerField(null=True)),
                ('directors', models.ManyToManyField(related_name='directors', to='coreapi.NameBasics')),
                ('writers', models.ManyToManyField(related_name='movies', to='coreapi.NameBasics')),
            ],
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('movieid', models.IntegerField()),
                ('imdbid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='link', serialize=False, to='coreapi.TitleAkas')),
                ('imagelink', models.URLField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TitleBasics',
            fields=[
                ('tconst', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='basics', serialize=False, to='coreapi.TitleAkas')),
                ('titletype', models.TextField(null=True)),
                ('primarytitle', models.TextField(null=True)),
                ('originaltitle', models.TextField(null=True)),
                ('isadult', models.IntegerField(null=True)),
                ('startyear', models.IntegerField(null=True)),
                ('endyear', models.TextField(null=True)),
                ('runtimeminutes', models.IntegerField(null=True)),
                ('genres', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TitlePrincipals',
            fields=[
                ('titleakas', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='members', serialize=False, to='coreapi.TitleAkas')),
                ('ordering', models.IntegerField()),
                ('category', models.TextField(blank=True, null=True)),
                ('job', models.TextField(blank=True, null=True)),
                ('characters', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TitleRatings',
            fields=[
                ('titleakas', models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='rating', serialize=False, to='coreapi.TitleAkas')),
                ('averagerating', models.FloatField(blank=True, null=True)),
                ('numvotes', models.IntegerField(null=True)),
            ],
        ),
        migrations.AddIndex(
            model_name='namebasics',
            index=models.Index(fields=['nconst'], name='coreapi_nam_nconst_1e543b_idx'),
        ),
        migrations.AddIndex(
            model_name='namebasics',
            index=models.Index(fields=['primaryname'], name='coreapi_nam_primary_cb2669_idx'),
        ),
        migrations.AddIndex(
            model_name='titleratings',
            index=models.Index(fields=['titleakas'], name='coreapi_tit_titleak_b42c03_idx'),
        ),
        migrations.AddField(
            model_name='titleprincipals',
            name='namebasics',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='works', to='coreapi.NameBasics'),
        ),
        migrations.AddIndex(
            model_name='titlebasics',
            index=models.Index(fields=['tconst'], name='coreapi_tit_tconst__7bc242_idx'),
        ),
        migrations.AddIndex(
            model_name='titlebasics',
            index=models.Index(fields=['originaltitle'], name='coreapi_tit_origina_264778_idx'),
        ),
        migrations.AddIndex(
            model_name='titlebasics',
            index=models.Index(fields=['primarytitle'], name='coreapi_tit_primary_c9553f_idx'),
        ),
        migrations.AddIndex(
            model_name='titleakas',
            index=models.Index(fields=['titleid', 'ordering'], name='coreapi_tit_titleid_c174d2_idx'),
        ),
        migrations.AddIndex(
            model_name='titleakas',
            index=models.Index(fields=['title'], name='coreapi_tit_title_61c1a5_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='titleakas',
            unique_together={('titleid', 'ordering')},
        ),
        migrations.AddIndex(
            model_name='link',
            index=models.Index(fields=['movieid'], name='coreapi_lin_movieid_aedf41_idx'),
        ),
        migrations.AddIndex(
            model_name='link',
            index=models.Index(fields=['imdbid'], name='coreapi_lin_imdbid__47c89e_idx'),
        ),
        migrations.AddIndex(
            model_name='titleprincipals',
            index=models.Index(fields=['titleakas', 'ordering'], name='coreapi_tit_titleak_b77f61_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='titleprincipals',
            unique_together={('titleakas', 'ordering')},
        ),
    ]
