# Generated by Django 3.0.6 on 2020-05-24 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NameBasics',
            fields=[
                ('nconst', models.TextField(primary_key=True, serialize=False)),
                ('primaryname', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TitleBasics',
            fields=[
                ('tconst', models.TextField(primary_key=True, serialize=False)),
                ('titletype', models.TextField(null=True)),
                ('primarytitle', models.TextField(null=True)),
                ('originaltitle', models.TextField(null=True)),
                ('isadult', models.IntegerField(null=True)),
                ('startyear', models.TextField(null=True)),
                ('endyear', models.IntegerField(null=True)),
                ('runtimeminutes', models.IntegerField(null=True)),
                ('genres', models.TextField(null=True)),
                ('imagelink', models.URLField(null=True)),
                ('directors', models.ManyToManyField(related_name='movies', to='coreapi.NameBasics')),
                ('writers', models.ManyToManyField(related_name='writers', to='coreapi.NameBasics')),
            ],
        ),
        migrations.CreateModel(
            name='TitleRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('averagerating', models.FloatField(null=True)),
                ('numofvotes', models.IntegerField(null=True)),
                ('imdbid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rating', to='coreapi.TitleBasics')),
            ],
        ),
        migrations.CreateModel(
            name='TitlePrincipals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordering', models.IntegerField()),
                ('category', models.TextField(null=True)),
                ('job', models.TextField(null=True)),
                ('characters', models.TextField(null=True)),
                ('nconst', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coreapi.NameBasics')),
                ('tconst', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crew', to='coreapi.TitleBasics')),
            ],
        ),
        migrations.CreateModel(
            name='TitleAkas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordering', models.IntegerField()),
                ('localtitle', models.TextField(null=True)),
                ('region', models.TextField(null=True)),
                ('language', models.TextField(null=True)),
                ('type', models.TextField(null=True)),
                ('attributes', models.TextField(null=True)),
                ('original', models.TextField(null=True)),
                ('tconst', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coreapi.TitleBasics')),
            ],
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movieid', models.IntegerField()),
                ('imdbid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='coreapi.TitleBasics')),
            ],
        ),
    ]
