# Generated by Django 3.0.6 on 2020-05-24 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapi', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='link',
            index=models.Index(fields=['movieid'], name='coreapi_lin_movieid_aedf41_idx'),
        ),
        migrations.AddIndex(
            model_name='link',
            index=models.Index(fields=['imdbid'], name='coreapi_lin_imdbid__47c89e_idx'),
        ),
        migrations.AddIndex(
            model_name='namebasics',
            index=models.Index(fields=['nconst'], name='coreapi_nam_nconst_1e543b_idx'),
        ),
        migrations.AddIndex(
            model_name='namebasics',
            index=models.Index(fields=['primaryname'], name='coreapi_nam_primary_cb2669_idx'),
        ),
        migrations.AddIndex(
            model_name='titleakas',
            index=models.Index(fields=['tconst'], name='coreapi_tit_tconst__992b14_idx'),
        ),
        migrations.AddIndex(
            model_name='titlebasics',
            index=models.Index(fields=['tconst'], name='coreapi_tit_tconst_6e91fe_idx'),
        ),
        migrations.AddIndex(
            model_name='titlebasics',
            index=models.Index(fields=['primarytitle'], name='coreapi_tit_primary_c9553f_idx'),
        ),
        migrations.AddIndex(
            model_name='titlebasics',
            index=models.Index(fields=['originaltitle'], name='coreapi_tit_origina_264778_idx'),
        ),
        migrations.AddIndex(
            model_name='titleprincipals',
            index=models.Index(fields=['tconst'], name='coreapi_tit_tconst__6413a7_idx'),
        ),
        migrations.AddIndex(
            model_name='titleprincipals',
            index=models.Index(fields=['nconst'], name='coreapi_tit_nconst__1e462a_idx'),
        ),
        migrations.AddIndex(
            model_name='titlerating',
            index=models.Index(fields=['imdbid'], name='coreapi_tit_imdbid__d624fc_idx'),
        ),
    ]
